name: ifc_converter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=3.0.3
  - numpy=2.0.2
  - gunicorn=23.0.0
  - shapely=2.0.7
  - pip=23.0
  - pip:
    - flask-login==0.6.3
    - flask-wtf==1.2.1
    - email-validator==2.1.0
    - python-dotenv==1.0.1
    - ifcopenshell==0.8.1.post1
    - git+https://github.com/IfcOpenShell/IfcOpenShell.git@09a43f13395ff23b237b0429a21e28fa6b190fda