services:
  - type: web
    name: ifc-converter
    env: python
    buildCommand: |
      # システムの依存パッケージをインストール
      apt-get update && apt-get install -y \
        build-essential \
        cmake \
        libboost-all-dev \
        python3-dev
      
      # Python環境のセットアップ
      python -m venv .venv
      . .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      . .venv/bin/activate
      cd /opt/render/project/src && exec gunicorn "ifc_app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.21
      - key: PYTHONPATH
        value: .
    healthCheckPath: /